version: "3.9"

services:
  postgres:
    container_name: users_postgres
    image: postgres:14.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432

  application:
    container_name: users_application
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - NODE_ENV=dockerdev
    volumes:
      - ./:/app/:ro